// Code generated by MockGen. DO NOT EDIT.
// Source: docbase.go

// Package mock_docbase is a generated GoMock package.
package mock_docbase

import (
	gomock "github.com/golang/mock/gomock"
	docbase "github.com/hayashiki/docbase-go"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// PostList mocks base method
func (m *MockClient) PostList(q string) ([]*docbase.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostList", q)
	ret0, _ := ret[0].([]*docbase.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostList indicates an expected call of PostList
func (mr *MockClientMockRecorder) PostList(q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostList", reflect.TypeOf((*MockClient)(nil).PostList), q)
}

// Download mocks base method
func (m *MockClient) Download(attachmentID string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", attachmentID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download
func (mr *MockClientMockRecorder) Download(attachmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockClient)(nil).Download), attachmentID)
}
