// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_elasticsearch is a generated GoMock package.
package mock_elasticsearch

import (
	gomock "github.com/golang/mock/gomock"
	entity "github.com/hayashiki/lemur/entity"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// SaveArticleDocument mocks base method
func (m *MockRepository) SaveArticleDocument(input *entity.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveArticleDocument", input)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveArticleDocument indicates an expected call of SaveArticleDocument
func (mr *MockRepositoryMockRecorder) SaveArticleDocument(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveArticleDocument", reflect.TypeOf((*MockRepository)(nil).SaveArticleDocument), input)
}
